base:
  project: churn-processing
  random_state: 42
  target_col: Churn

raw_data:
  raw_dataset: raw_data/customer_churn.csv

processed_data:
  processed_dataset: processed_data/cleaned_data.csv

estimators:
  LogisticRegression:
    params:
      penalty: [ 'l2' ]
  DecisionTrees:
    params:
      criterion: [ 'gini','entropy' ]
      splitter: [ 'best', 'random' ]
      max_depth: [ 5,10,15,20,25,30,40,50 ]
      min_samples_leaf: [ 1,2,3,4,5 ]
  RandomForest:
    params:
      n_estimators: [ 10,15,20,25,30,35,40,50,55,60,70,75,80,85,90,95,100 ]
      criterion: [ 'gini','entropy' ]
      max_depth: [ 5,10,15,20,25,30,40,50 ]
      min_samples_leaf: [ 1,2,3,4,5 ]


model_dir: saved_models

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: Churn Processing Experiment
  run_name: mlops
  registered_model_name: ChurnProcessingModel
  remote_server_uri: http://127.0.0.1:1234

